Parameters:
  TargetAccounts:
    Type: List<String>
    Default: xx,xx,xx

Resources:
  GuardDutyMembers:
    Type: 'AWS::CloudFormation::StackSet'
    Properties:
      PermissionModel: SELF_MANAGED

      StackSetName: GuardDutyMembers
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts: !Ref TargetAccounts
          Regions:
            - !Ref AWS::Region
      TemplateBody: |
        Resources:
          Detector:
            Type: AWS::GuardDuty::Detector
            Properties:
              DataSources:
                S3Logs:
                  Enable: true
              Enable: true
              FindingPublishingFrequency: FIFTEEN_MINUTES